Started by user [8mha:////4AvbKtqCpWGC4/9vlaAOyQD+y56HOfLOpPpkD7K9YRsAAAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzWEgZu/dLi1CL9xJTczDwAj6GcLcAAAAA=[0madmin
Running as SYSTEM
Building in workspace /var/root/.jenkins/workspace/data-minyao
using credential root
Cloning the remote Git repository
Cloning repository git@github.com:kirinisland/datapipe.git
 > git init /var/root/.jenkins/workspace/data-minyao # timeout=10
Fetching upstream changes from git@github.com:kirinisland/datapipe.git
 > git --version # timeout=10
using GIT_SSH to set credentials 
 > git fetch --tags --force --progress -- git@github.com:kirinisland/datapipe.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url git@github.com:kirinisland/datapipe.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url git@github.com:kirinisland/datapipe.git # timeout=10
Fetching upstream changes from git@github.com:kirinisland/datapipe.git
using GIT_SSH to set credentials 
 > git fetch --tags --force --progress -- git@github.com:kirinisland/datapipe.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision ca49a7d2f48e4a31b3d0bda9a079340aef4fd65b (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f ca49a7d2f48e4a31b3d0bda9a079340aef4fd65b # timeout=10
Commit message: "update sleep time back"
 > git rev-list --no-walk ca49a7d2f48e4a31b3d0bda9a079340aef4fd65b # timeout=10
[data-minyao] $ /bin/sh -xe /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/jenkins86071854594133608.sh
+ '[' false = true ']'
+ echo 'Fetch without proxy!'
Fetch without proxy!
+ python3 runner_qq.py --method search --query $'\346\260\221\350\260\243' --output-suffix minyao --dump-raw 1 --dump-seg 0
INFO:[DataPipeline]:Start crawling for query: 民谣
INFO:[DataPipeline]:Processing playlist page: 0, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 1, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 2, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 3, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 4, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 5, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 6, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 7, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 8, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 9, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 10, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 11, found 48 playlists
INFO:[DataPipeline]:Processing playlist page: 12, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 13, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 14, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 15, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 16, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 17, found 49 playlists
INFO:[DataPipeline]:Processing playlist page: 18, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 19, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 20, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 21, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 22, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 23, found 50 playlists
INFO:[DataPipeline]:Processing playlist page: 24, found 28 playlists
INFO:[DataPipeline]:Processing playlist page: 25, found 18 playlists
INFO:[DataPipeline]:Processing playlist page: 26, found 21 playlists
INFO:[DataPipeline]:Processing playlist page: 27, found 1 playlists
INFO:[DataPipeline]:Processing playlist page: 28, found 21 playlists
INFO:[DataPipeline]:Processing playlist page: 29, found 20 playlists
INFO:[DataPipeline]:Processing playlist page: 30, found 21 playlists
INFO:[DataPipeline]:Processing playlist page: 31, found 21 playlists
INFO:[DataPipeline]:Processing playlist page: 32, found 3 playlists
INFO:[DataPipeline]:Processing playlist page: 33, found 44 playlists
INFO:[DataPipeline]:Processing playlist page: 34, found 43 playlists
INFO:[DataPipeline]:Processing playlist page: 35, found 0 playlists
INFO:[DataPipeline]:Total playlists found about topic: 民谣: 1427
INFO:[DataPipeline]:PlayList: [7269560843] 华语&#124;&#32;民谣在路上 (0/1427) has 30 songs.
INFO:[DataPipeline]:PlayList: [7280726307] 华语&#32;&#124;&#32;暖心民谣 (1/1427) has 29 songs.
INFO:[DataPipeline]:PlayList: [7467921369] 免费下载的诗意民谣你值得收藏 (2/1427) has 64 songs.
INFO:[DataPipeline]:PlayList: [5109299040] 民谣诗酒铺 (3/1427) has 33 songs.
INFO:[DataPipeline]:PlayList: [7372131334] 民谣男声：我的心上人，你在何方 (4/1427) has 20 songs.
INFO:[DataPipeline]:PlayList: [7344474241] 民谣男声&#32;·&#32;屏蔽纷纷扰扰 (5/1427) has 22 songs.
INFO:[DataPipeline]:PlayList: [6947366186] 晚班归家途中的暖心民谣 (6/1427) has 47 songs.
INFO:[DataPipeline]:PlayList: [7275444654] 华语民谣&#124;&#32;理想志 (7/1427) has 22 songs.
INFO:[DataPipeline]:PlayList: [7023269050] 民谣&#32;·&#32;一人独享安静时刻 (8/1427) has 20 songs.
INFO:[DataPipeline]:PlayList: [7270854675] 华语民谣&#32;&#124;&#32;或许你也听过 (9/1427) has 32 songs.
INFO:[DataPipeline]:Sleep for: 54
INFO:[DataPipeline]:PlayList: [6967377538] 清新民谣&#32;·&#32;让夏日不再燥热 (10/1427) has 20 songs.
INFO:[DataPipeline]:PlayList: [6985347879] 华语民谣：故事和你，如酒浓烈 (11/1427) has 26 songs.
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/Library/Python/3.7/site-packages/urllib3/connection.py", line 360, in connect
    ssl_context=context,
  File "/Library/Python/3.7/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1039: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Library/Python/3.7/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Library/Python/3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 379, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 331, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner_qq.py", line 60, in process_playlist
    lyric = api.get_song_lyric(song.id)
  File "/private/var/root/.jenkins/workspace/data-minyao/dao/qq_api.py", line 43, in get_song_lyric
    raw_text = self.fetch_raw(url)
  File "/private/var/root/.jenkins/workspace/data-minyao/dao/base_api.py", line 34, in fetch_raw
    verify=False)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='c.y.qq.com', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "runner_qq.py", line 158, in <module>
    main()
  File "runner_qq.py", line 145, in main
    args.proxy, logger, args.dump_raw, args.dump_seg)
  File "runner_qq.py", line 70, in process_playlist
    logger.error("Exception in processing songs: ", err)
Message: 'Exception in processing songs: '
Arguments: (ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='c.y.qq.com', port=443): Read timed out. (read timeout=30)")),)
INFO:[DataPipeline]:PlayList: [861218535] 400位华语民谣歌手，一人一首入耳曲 (12/1427) has 400 songs.
INFO:[DataPipeline]:PlayList: [7026150751] 民谣&#32;&#124;&#32;没有你&#32;故事哪有结尾 (13/1427) has 45 songs.
INFO:[DataPipeline]:PlayList: [7365352274] 民谣男声：唱给你心中的那个女孩 (14/1427) has 20 songs.
INFO:[DataPipeline]:PlayList: [3772360534] 伤感民谣：姑娘我想你，你可知道 (15/1427) has 21 songs.
INFO:[DataPipeline]:PlayList: [7064172394] 民谣&#32;·&#32;四海为家，各安天下 (16/1427) has 30 songs.
INFO:[DataPipeline]:PlayList: [7278376187] 华语民谣&#32;&#124;&#32;悠闲时光 (17/1427) has 28 songs.
INFO:[DataPipeline]:PlayList: [7043128804] &#32;民谣博物馆：诗人的轻快空间 (18/1427) has 30 songs.
INFO:[DataPipeline]:PlayList: [7270869375] 华语民谣&#32;&#124;&#32;低吟浅唱 (19/1427) has 28 songs.
INFO:[DataPipeline]:Sleep for: 155
INFO:[DataPipeline]:PlayList: [7052176045] 华语民谣&#32;·&#32;安抚疲惫的心 (20/1427) has 20 songs.
INFO:[DataPipeline]:PlayList: [6638891608] 清新民谣&#32;：夏日树荫里的惬意 (21/1427) has 43 songs.
INFO:[DataPipeline]:PlayList: [7190702514] 民谣故事：想把我唱给你听 (22/1427) has 20 songs.
INFO:[DataPipeline]:PlayList: [7217122000] 温柔民谣：直抵内心柔软处 (23/1427) has 31 songs.
INFO:[DataPipeline]:PlayList: [6928423659] 恋恋民谣&#32;&#124;&#32;轻拨琴弦，说我爱你 (24/1427) has 23 songs.
INFO:[DataPipeline]:PlayList: [7270872159] 华语民谣&#32;&#124;&#32;青葱记忆 (25/1427) has 27 songs.
INFO:[DataPipeline]:PlayList: [7271047439] 华语民谣&#32;&#124;&#32;日光正好 (26/1427) has 27 songs.
INFO:[DataPipeline]:PlayList: [7271051209] 华语民谣&#32;&#124;&#32;回家路上 (27/1427) has 27 songs.
INFO:[DataPipeline]:PlayList: [7278384968] 民谣&#32;&#124;&#32;晒个太阳暖洋洋 (28/1427) has 22 songs.
INFO:[DataPipeline]:PlayList: [7075723697] 民谣不是陈词滥调，只是故事发了酵 (29/1427) has 52 songs.
INFO:[DataPipeline]:Sleep for: 41
INFO:[DataPipeline]:PlayList: [7285148674] 民谣&#32;·&#32;和你书写平淡爱情 (30/1427) has 20 songs.
INFO:[DataPipeline]:PlayList: [7074538435] 深情民谣丨暖阳温柔似君心 (31/1427) has 35 songs.
INFO:[DataPipeline]:PlayList: [3722109963] 冷门民谣：与“众”不同&#32; (32/1427) has 21 songs.
INFO:[DataPipeline]:PlayList: [6948765328] 华语民谣：藏在故事里的姑娘 (33/1427) has 78 songs.
INFO:[DataPipeline]:PlayList: [7270870842] 华语民谣&#32;&#124;&#32;可爱的你 (34/1427) has 27 songs.
INFO:[DataPipeline]:PlayList: [6929880835] 民谣纪念册&#32;&#58;&#32;春暖花开，思念成海 (35/1427) has 32 songs.
INFO:[DataPipeline]:PlayList: [7252361810] 民谣丨独自听遍人间故事 (36/1427) has 38 songs.
INFO:[DataPipeline]:PlayList: [7265381810] 欧美民谣，远离喧嚣的静谧小镇 (37/1427) has 21 songs.
INFO:[DataPipeline]:PlayList: [7228612607] 一首民谣，逃离偌大的城市 (38/1427) has 39 songs.
INFO:[DataPipeline]:PlayList: [7189426304] 五味杂陈：总有一首民谣是解药 (39/1427) has 34 songs.
INFO:[DataPipeline]:Sleep for: 165
INFO:[DataPipeline]:PlayList: [6917207230] 佛系民谣&#32;：闭眼看世界 (40/1427) has 33 songs.
INFO:[DataPipeline]:PlayList: [7271049341] 华语民谣&#32;&#124;&#32;且听风吟 (41/1427) has 25 songs.
INFO:[DataPipeline]:PlayList: [6957903200] 轻快民谣&#32;·&#32;草莓味小情歌 (42/1427) has 22 songs.
INFO:[DataPipeline]:PlayList: [7270385730] 华语民谣&#124;&#32;在异乡 (43/1427) has 22 songs.
INFO:[DataPipeline]:PlayList: [7068094876] 民谣：十里春风，不及你扣弦一语 (44/1427) has 46 songs.
INFO:[DataPipeline]:PlayList: [7072786380] 舒心民谣：减燥的清凉味道 (45/1427) has 42 songs.
INFO:[DataPipeline]:PlayList: [7228610527] 民谣&#32;&#124;&#32;一帆风顺那就不叫生活了 (46/1427) has 36 songs.
INFO:[DataPipeline]:PlayList: [6987887236] 心酸民谣｜孤独诗人颠簸故事 (47/1427) has 39 songs.
INFO:[DataPipeline]:PlayList: [7004322047] 微醺烟嗓民谣&#32;&#124;&#32;听到醉时方解忧 (48/1427) has 25 songs.
INFO:[DataPipeline]:PlayList: [7097547552] 治愈民谣，闪烁在心底的萤火 (49/1427) has 25 songs.
INFO:[DataPipeline]:Sleep for: 95
INFO:[DataPipeline]:PlayList: [7024582292] 静心民谣：夏日清凉专享 (50/1427) has 28 songs.
INFO:[DataPipeline]:PlayList: [7021918213] 中国风民谣&#32;&#124;&#32;弹指间，千年逝 (51/1427) has 28 songs.
INFO:[DataPipeline]:PlayList: [6964018684] 茶凉可续&#32;·&#32;寄于民谣中的孤独 (52/1427) has 31 songs.
INFO:[DataPipeline]:PlayList: [7086641073] 睡前小曲&#32;·&#32;苦味民谣伴你入梦 (53/1427) has 20 songs.
INFO:[DataPipeline]:PlayList: [6947819714] 睡前民谣&#32;·&#32;享受夜晚的宁谧 (54/1427) has 25 songs.
INFO:[DataPipeline]:PlayList: [7038182843] 民谣丨唱生活本来的样子 (55/1427) has 27 songs.
INFO:[DataPipeline]:PlayList: [7222869273] 小众民谣&#32;&#124;&#32;生活最初的模样 (56/1427) has 31 songs.
INFO:[DataPipeline]:PlayList: [7276455197] 华语民谣&#124;&#32;枕边随想 (57/1427) has 21 songs.
INFO:[DataPipeline]:PlayList: [813783126] 听了这些歌爱上了民谣 (58/1427) has 100 songs.
INFO:[DataPipeline]:PlayList: [6928005649] 吟游诗人&#32;&#124;&#32;风中颂唱异国民谣&#32; (59/1427) has 26 songs.
INFO:[DataPipeline]:Sleep for: 155
INFO:[DataPipeline]:PlayList: [6911101421] 华语民谣&#32;&#58;&#32;把名字记述在歌里 (60/1427) has 36 songs.
INFO:[DataPipeline]:PlayList: [7038772310] 小资情调&#32;·&#32;咖啡馆静心民谣 (61/1427) has 24 songs.
INFO:[DataPipeline]:PlayList: [7097402732] 烟嗓民谣丨云里雾里，尽在眼里 (62/1427) has 88 songs.
INFO:[DataPipeline]:PlayList: [7094416356] 暖心民谣&#32;&#58;&#32;这一生关于你的风景 (63/1427) has 19 songs.
INFO:[DataPipeline]:PlayList: [6998129452] 未实现的梦想，都谱成了民谣 (64/1427) has 35 songs.
INFO:[DataPipeline]:PlayList: [4227252301] 适合在移动K房里唱的华语民谣 (65/1427) has 35 songs.
INFO:[DataPipeline]:PlayList: [7019488378] 民谣情信&#32;&#58;&#32;予你手心的温暖 (66/1427) has 28 songs.
INFO:[DataPipeline]:PlayList: [3762511678] 「抖音」抖友都在听的热门华语民谣 (67/1427) has 173 songs.
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Library/Python/3.7/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Library/Python/3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 331, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner_qq.py", line 60, in process_playlist
    lyric = api.get_song_lyric(song.id)
  File "/private/var/root/.jenkins/workspace/data-minyao/dao/qq_api.py", line 43, in get_song_lyric
    raw_text = self.fetch_raw(url)
  File "/private/var/root/.jenkins/workspace/data-minyao/dao/base_api.py", line 34, in fetch_raw
    verify=False)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='c.y.qq.com', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "runner_qq.py", line 158, in <module>
    main()
  File "runner_qq.py", line 145, in main
    args.proxy, logger, args.dump_raw, args.dump_seg)
  File "runner_qq.py", line 70, in process_playlist
    logger.error("Exception in processing songs: ", err)
Message: 'Exception in processing songs: '
Arguments: (ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='c.y.qq.com', port=443): Read timed out. (read timeout=30)")),)
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/Library/Python/3.7/site-packages/urllib3/connection.py", line 360, in connect
    ssl_context=context,
  File "/Library/Python/3.7/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1039: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Library/Python/3.7/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Library/Python/3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 379, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 331, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner_qq.py", line 60, in process_playlist
    lyric = api.get_song_lyric(song.id)
  File "/private/var/root/.jenkins/workspace/data-minyao/dao/qq_api.py", line 43, in get_song_lyric
    raw_text = self.fetch_raw(url)
  File "/private/var/root/.jenkins/workspace/data-minyao/dao/base_api.py", line 34, in fetch_raw
    verify=False)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='c.y.qq.com', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "runner_qq.py", line 158, in <module>
    main()
  File "runner_qq.py", line 145, in main
    args.proxy, logger, args.dump_raw, args.dump_seg)
  File "runner_qq.py", line 70, in process_playlist
    logger.error("Exception in processing songs: ", err)
Message: 'Exception in processing songs: '
Arguments: (ReadTimeout(ReadTimeoutError("HTTPSConnectionPool(host='c.y.qq.com', port=443): Read timed out. (read timeout=30)")),)
INFO:[DataPipeline]:PlayList: [2370564757] 「民谣」是毒药，也是良药 (68/1427) has 99 songs.
INFO:[DataPipeline]:PlayList: [2058943165] 民谣集：20岁时变成了一个用故事下酒的人 (69/1427) has 109 songs.
INFO:[DataPipeline]:Sleep for: 139
INFO:[DataPipeline]:PlayList: [2932135401] 吉他伴民谣：50首关于青年的暖心诗 (70/1427) has 50 songs.
INFO:[DataPipeline]:PlayList: [2372160429] 没有流量也要下载的100首欧美民谣 (71/1427) has 103 songs.
INFO:[DataPipeline]:PlayList: [1135117913] 编辑推荐｜民谣女声，惊艳透彻声线 (72/1427) has 50 songs.
INFO:[DataPipeline]:PlayList: [3536845247] 欧美｜清透舒适的民谣小调 (73/1427) has 40 songs.
INFO:[DataPipeline]:PlayList: [2273669640] 小米粥式民谣：午休时段的清凉调 (74/1427) has 51 songs.
INFO:[DataPipeline]:PlayList: [3269004721] 民谣如酒&#32;入喉醉心 (75/1427) has 251 songs.
