Started by user [8mha:////4AvbKtqCpWGC4/9vlaAOyQD+y56HOfLOpPpkD7K9YRsAAAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzWEgZu/dLi1CL9xJTczDwAj6GcLcAAAAA=[0madmin
Running as SYSTEM
Building in workspace /var/root/.jenkins/workspace/data_by_tag
using credential root
Cloning the remote Git repository
Cloning repository git@github.com:kirinisland/datapipe.git
 > git init /var/root/.jenkins/workspace/data_by_tag # timeout=10
Fetching upstream changes from git@github.com:kirinisland/datapipe.git
 > git --version # timeout=10
using GIT_SSH to set credentials 
 > git fetch --tags --force --progress -- git@github.com:kirinisland/datapipe.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url git@github.com:kirinisland/datapipe.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url git@github.com:kirinisland/datapipe.git # timeout=10
Fetching upstream changes from git@github.com:kirinisland/datapipe.git
using GIT_SSH to set credentials 
 > git fetch --tags --force --progress -- git@github.com:kirinisland/datapipe.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision 8862dc0b93faeb24f71cee4ff5c950ac2bc56c56 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 8862dc0b93faeb24f71cee4ff5c950ac2bc56c56 # timeout=10
Commit message: "update log"
 > git rev-list --no-walk 8862dc0b93faeb24f71cee4ff5c950ac2bc56c56 # timeout=10
[data_by_tag] $ /bin/sh -xe /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/jenkins2345884530331520572.sh
++ date +%Y%m%d
+ date_str=20200727
+ python3 runner_qq.py --method by_tag --tag 6 --output-suffix tag_english --dump-raw 1 --dump-seg 0 --proxy
INFO:[DataPipeline]:Processing tag : QQMusicTag.english
INFO:[DataPipeline]:Total playlists found about tag: [<QQMusicTag.english: (' 英语', 167)>]: 51
INFO:[DataPipeline]:PlayList: [7092582133] 电子梦境，让Drop点燃灵魂 (0/51) has 83 songs.
INFO:[DataPipeline]:PlayList: [7087298637] 假日派对｜欧美清凉小调 (1/51) has 33 songs.
INFO:[DataPipeline]:PlayList: [7085583499] 暮色似水，思念成海 (2/51) has 28 songs.
INFO:[DataPipeline]:PlayList: [7086008336] 恬静英文｜慵懒的午后 温柔似海风 (3/51) has 33 songs.
INFO:[DataPipeline]:PlayList: [7084030804] 治愈摇滚 | 没有暴躁，只有温柔 (4/51) has 38 songs.
INFO:[DataPipeline]:PlayList: [7086014743] 爵士柔情：你我氤氲漫舞 (5/51) has 26 songs.
INFO:[DataPipeline]:PlayList: [6675994191] 禁止想象 · 耳机里的万种风情 (6/51) has 32 songs.
INFO:[DataPipeline]:PlayList: [5109267378] 下班最来劲 (7/51) has 36 songs.
INFO:[DataPipeline]:PlayList: [6914150646] 你好披头士 (8/51) has 30 songs.
INFO:[DataPipeline]:PlayList: [7060897744] 电音宣泄・寻回内心缺失的安宁 (9/51) has 35 songs.
INFO:[DataPipeline]:Sleep for: 132
INFO:[DataPipeline]:PlayList: [7061099463] 志愿填报ing：怀揣希望徐徐前行 (10/51) has 26 songs.
INFO:[DataPipeline]:PlayList: [7107159327] 睡前治愈：小猪佩奇为你唱晚安曲 (11/51) has 59 songs.
INFO:[DataPipeline]:PlayList: [7058795239] 洗掉烦恼！ 沐浴搓澡更带感 (12/51) has 29 songs.
INFO:[DataPipeline]:PlayList: [7050345693] Gabber：从风靡到消逝 (13/51) has 25 songs.
INFO:[DataPipeline]:PlayList: [7052818442] 清晨元气弹 · 猪猪女孩起床铃 (14/51) has 22 songs.
INFO:[DataPipeline]:PlayList: [7096606332] 巴塔木：儿歌+动画，英语轻松学 (15/51) has 56 songs.
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 662, in urlopen
    self._prepare_proxy(conn)
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 948, in _prepare_proxy
    conn.connect()
  File "/Library/Python/3.7/site-packages/urllib3/connection.py", line 360, in connect
    ssl_context=context,
  File "/Library/Python/3.7/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1039: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Library/Python/3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=201942955&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner_qq.py", line 58, in process_playlist
    lyric = api.get_song_lyric(song.id)
  File "/private/var/root/.jenkins/workspace/data_by_tag/dao/qq_api.py", line 43, in get_song_lyric
    raw_text = self.fetch_raw(url)
  File "/private/var/root/.jenkins/workspace/data_by_tag/dao/base_api.py", line 34, in fetch_raw
    verify=False)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=201942955&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "runner_qq.py", line 158, in <module>
    main()
  File "runner_qq.py", line 154, in main
    args.proxy, logger, args.dump_raw, args.dump_seg)
  File "runner_qq.py", line 68, in process_playlist
    logger.error("Exception in processing songs: ", err)
Message: 'Exception in processing songs: '
Arguments: (ProxyError(MaxRetryError("HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=201942955&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))")),)
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 662, in urlopen
    self._prepare_proxy(conn)
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 948, in _prepare_proxy
    conn.connect()
  File "/Library/Python/3.7/site-packages/urllib3/connection.py", line 360, in connect
    ssl_context=context,
  File "/Library/Python/3.7/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1039: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Library/Python/3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=201942941&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner_qq.py", line 58, in process_playlist
    lyric = api.get_song_lyric(song.id)
  File "/private/var/root/.jenkins/workspace/data_by_tag/dao/qq_api.py", line 43, in get_song_lyric
    raw_text = self.fetch_raw(url)
  File "/private/var/root/.jenkins/workspace/data_by_tag/dao/base_api.py", line 34, in fetch_raw
    verify=False)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=201942941&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "runner_qq.py", line 158, in <module>
    main()
  File "runner_qq.py", line 154, in main
    args.proxy, logger, args.dump_raw, args.dump_seg)
  File "runner_qq.py", line 68, in process_playlist
    logger.error("Exception in processing songs: ", err)
Message: 'Exception in processing songs: '
Arguments: (ProxyError(MaxRetryError("HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=201942941&_=1513437581324 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))")),)
INFO:[DataPipeline]:PlayList: [7052301413] Glitch Hop：故障美学 (16/51) has 55 songs.
INFO:[DataPipeline]:PlayList: [7051781002] 落日余晖 · 悦享舒适民谣 (17/51) has 26 songs.
INFO:[DataPipeline]:PlayList: [7039483266] 小众但令人愉悦的国人英文歌 (18/51) has 34 songs.
INFO:[DataPipeline]:PlayList: [3948869431] 编辑推荐：经典民谣 (19/51) has 82 songs.
INFO:[DataPipeline]:Sleep for: 95
INFO:[DataPipeline]:PlayList: [7046927214] Hardcore: 黑暗沉浸的极致快感 (20/51) has 52 songs.
INFO:[DataPipeline]:PlayList: [7048898404] 再不去健身，健身卡要过期啦 (21/51) has 25 songs.
INFO:[DataPipeline]:PlayList: [7024329293] 欧美Remix：给曲库加点料 (22/51) has 142 songs.
INFO:[DataPipeline]:PlayList: [7048708076] 绝妙女声： 万物皆甜 (23/51) has 146 songs.
INFO:[DataPipeline]:PlayList: [7046669110] 优质欧美男声，轻松俘获你心 (24/51) has 28 songs.
INFO:[DataPipeline]:PlayList: [7051256059] 欧美摇滚 | 送你一台跳舞机 (25/51) has 23 songs.
INFO:[DataPipeline]:PlayList: [7059920058] Uplifting Trance · 异度冥想 (26/51) has 32 songs.
INFO:[DataPipeline]:PlayList: [5109263873] 热浪电音 (27/51) has 35 songs.
INFO:[DataPipeline]:PlayList: [7047402274] 【WWE精选】热血征程再度扬帆 (28/51) has 50 songs.
INFO:[DataPipeline]:PlayList: [7041169329] Country music · 假日二人世界 (29/51) has 22 songs.
INFO:[DataPipeline]:Sleep for: 171
INFO:[DataPipeline]:PlayList: [7050017336] 芬兰金属乐：狂野而典雅 (30/51) has 33 songs.
INFO:[DataPipeline]:PlayList: [7085217895] 美剧《危机边缘》原声插曲合集 (31/51) has 34 songs.
INFO:[DataPipeline]:PlayList: [7055881964] Future Bass · 未来之音 (32/51) has 70 songs.
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 662, in urlopen
    self._prepare_proxy(conn)
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 948, in _prepare_proxy
    conn.connect()
  File "/Library/Python/3.7/site-packages/urllib3/connection.py", line 360, in connect
    ssl_context=context,
  File "/Library/Python/3.7/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1056)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Python/3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Library/Python/3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=109191266&_=1513437581324 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1056)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runner_qq.py", line 58, in process_playlist
    lyric = api.get_song_lyric(song.id)
  File "/private/var/root/.jenkins/workspace/data_by_tag/dao/qq_api.py", line 43, in get_song_lyric
    raw_text = self.fetch_raw(url)
  File "/private/var/root/.jenkins/workspace/data_by_tag/dao/base_api.py", line 34, in fetch_raw
    verify=False)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=109191266&_=1513437581324 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1056)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 619, in format
    record.message = record.getMessage()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "runner_qq.py", line 158, in <module>
    main()
  File "runner_qq.py", line 154, in main
    args.proxy, logger, args.dump_raw, args.dump_seg)
  File "runner_qq.py", line 68, in process_playlist
    logger.error("Exception in processing songs: ", err)
Message: 'Exception in processing songs: '
Arguments: (SSLError(MaxRetryError("HTTPSConnectionPool(host='c.y.qq.com', port=443): Max retries exceeded with url: /lyric/fcgi-bin/fcg_query_lyric.fcg?g_tk=5381&format=json&inCharset=utf-8&outCharset=utf-8&platform=h5&needNewCode=1&nobase64=1&musicid=109191266&_=1513437581324 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1056)')))")),)
INFO:[DataPipeline]:PlayList: [7027679656] 英伦元气之声：We Got The Power ! (33/51) has 20 songs.
INFO:[DataPipeline]:PlayList: [7082807272] 小众欧美 | 清晨的第一缕美好 (34/51) has 72 songs.
INFO:[DataPipeline]:PlayList: [6951904993] 致瘾电子：震撼心灵的惊艳嗓音 (35/51) has 126 songs.
INFO:[DataPipeline]:PlayList: [7048891820] 女声摇滚：另类狂野躁动你心 (36/51) has 28 songs.
INFO:[DataPipeline]:PlayList: [7050093670] Synthwave：未来复古音乐美学 (37/51) has 45 songs.
INFO:[DataPipeline]:PlayList: [7038078776] 我洗头的时候会点开这个歌单 (38/51) has 37 songs.
INFO:[DataPipeline]:PlayList: [7027581103] 欧美R&B：温软旋律缭绕耳边 (39/51) has 31 songs.
INFO:[DataPipeline]:Sleep for: 67
INFO:[DataPipeline]:PlayList: [7031063906] 压箱宝藏！ 欧美空灵女声 (40/51) has 28 songs.
INFO:[DataPipeline]:PlayList: [7039837201] Hip Hop:街头涂鸦演绎嘻哈艺术 (41/51) has 88 songs.
INFO:[DataPipeline]:PlayList: [7014817266] 毒性电音 · 致幻女嗓 (42/51) has 125 songs.
INFO:[DataPipeline]:PlayList: [6929499876] Elysian Records: 拍手厂作品合集 (43/51) has 106 songs.
INFO:[DataPipeline]:PlayList: [7055960914] Deep House · 陷落低频天堂 (44/51) has 28 songs.
INFO:[DataPipeline]:PlayList: [7061512987] 清爽remix ：夏日透心凉 (45/51) has 55 songs.
INFO:[DataPipeline]:PlayList: [7085681191] 深夜音“药”： 激活你的学习脑细胞 (46/51) has 72 songs.
INFO:[DataPipeline]:PlayList: [7055774196] Sadcore | 忧郁的靡靡之音 (47/51) has 24 songs.
INFO:[DataPipeline]:PlayList: [7026475859] 璀璨夜空 · 引落星煜的梦幻电子 (48/51) has 53 songs.
INFO:[DataPipeline]:PlayList: [7088434129] 工作力Max：任务未完我不能倒！ (49/51) has 23 songs.
INFO:[DataPipeline]:Sleep for: 115
INFO:[DataPipeline]:PlayList: [7050203809] 金属摇滚 | 狂野呐喊下的不羁灵魂 (50/51) has 25 songs.
Finished: SUCCESS
